# Generated by Django 4.1.5 on 2023-02-02 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(default='', unique=True)),
                ('store_type', models.CharField(choices=[('RETAILE', 'RETAILE'), ('WHOLESALE', 'WHOLESALE'), ('MANUFACTURE', 'MANUFACTURE')], default='RETAILE', max_length=255)),
                ('store_logo', models.ImageField(default='', upload_to='images/logo')),
                ('store_banner', models.ImageField(default='', upload_to='images/banner')),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
