# Generated by Django 4.1.5 on 2023-02-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(default='', unique=True)),
                ('product_image', models.ImageField(default='', upload_to='images/products')),
                ('product_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeapi.storedata')),
            ],
        ),
    ]
